//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VLStoreModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsProviders
    {
        public string Reference { get; set; }
        public string ProviderCode { get; set; }
        public string ProviderReference { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> DeliveryDays { get; set; }
        public Nullable<bool> DefaultProvider { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Temp_Providers Temp_Providers { get; set; }
    }
}
