//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VLStoreModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.InventoryProducts = new HashSet<InventoryProducts>();
            this.ProductsProviders = new HashSet<ProductsProviders>();
            this.RegularizationProducts = new HashSet<RegularizationProducts>();
        }
    
        public string Reference { get; set; }
        public string ProductName { get; set; }
        public int IdType { get; set; }
        public Nullable<bool> UseExpirationDate { get; set; }
        public Nullable<bool> UseLot { get; set; }
        public Nullable<double> StockMin { get; set; }
        public Nullable<double> QuantityInUse { get; set; }
        public Nullable<bool> WarningForMinStock { get; set; }
        public string Dimensions { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryProducts> InventoryProducts { get; set; }
        public virtual ProductTypes ProductTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductsProviders> ProductsProviders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegularizationProducts> RegularizationProducts { get; set; }
        public virtual Products Products1 { get; set; }
        public virtual Products Products2 { get; set; }
    }
}
