//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VLStoreModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Regularizations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Regularizations()
        {
            this.RegularizationProducts = new HashSet<RegularizationProducts>();
        }
    
        public int IdRegularization { get; set; }
        public int IdStore { get; set; }
        public string TypeMovement { get; set; }
        public System.DateTime RegularizationDate { get; set; }
        public string RegularizationUser { get; set; }
        public string Remarks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegularizationProducts> RegularizationProducts { get; set; }
        public virtual Stores Stores { get; set; }
        public virtual Temp_Employees Temp_Employees { get; set; }
    }
}
