//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VLStoreModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stores()
        {
            this.Inventory = new HashSet<Inventory>();
            this.Regularizations = new HashSet<Regularizations>();
            this.StoreLocations = new HashSet<StoreLocations>();
        }
    
        public int IdStore { get; set; }
        public string StoreName { get; set; }
        public string StoreDescription { get; set; }
        public string Owner { get; set; }
        public string Area { get; set; }
        public string StoreLocation { get; set; }
        public string Remarks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventory> Inventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Regularizations> Regularizations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoreLocations> StoreLocations { get; set; }
        public virtual Temp_Employees Temp_Employees { get; set; }
        public virtual Stores Stores1 { get; set; }
        public virtual Stores Stores2 { get; set; }
        public virtual Temp_Areas Temp_Areas { get; set; }
    }
}
