//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VLStoreModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreLocations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StoreLocations()
        {
            this.InventoryProducts = new HashSet<InventoryProducts>();
            this.RegularizationProducts = new HashSet<RegularizationProducts>();
        }
    
        public int IdStore { get; set; }
        public string LocationCode { get; set; }
        public string LocationDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryProducts> InventoryProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegularizationProducts> RegularizationProducts { get; set; }
        public virtual Stores Stores { get; set; }
    }
}
