//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VLStoreModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_Areas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Temp_Areas()
        {
            this.Stores = new HashSet<Stores>();
        }
    
        public string WorkingAreaName { get; set; }
        public string WorkingArea { get; set; }
        public string Telephone { get; set; }
        public string State { get; set; }
        public string PostalZIP { get; set; }
        public string Fax { get; set; }
        public string Country { get; set; }
        public string Contact { get; set; }
        public string Company { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stores> Stores { get; set; }
    }
}
