//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VLStoreModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vInventoryProducts
    {
        public int IdInventory { get; set; }
        public string Expr1 { get; set; }
        public string Expr2 { get; set; }
        public string Location { get; set; }
        public double Quantity { get; set; }
        public string Lot { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
    }
}
