//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VLStoreModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vRegularizationProducts
    {
        public string Reference { get; set; }
        public string ProductName { get; set; }
        public int IdRegularization { get; set; }
        public int IdStore { get; set; }
        public string Location { get; set; }
    }
}
